---
title: "passwords"
author: "Marisa Henry"
date: "1/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(assertthat)
library(patchwork)
library(plotMPR)
extrafont::loadfonts(device = "win", quiet = TRUE)

passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv') %>% filter(!is.na(password))

passwords <- passwords %>%
  mutate(letters_only = grepl('^[A-Za-z]*$', password), 
         num_only = grepl('^[0-9]*$', password), 
         alphanumeric = if_else(letters_only + num_only == 0, TRUE, FALSE)) 

# not sure I trust my regex!
assertthat::assert_that(all(rowSums(passwords %>% select(letters_only, num_only, alphanumeric))) == 1)

passwords <- passwords %>%
  gather(type, flag, letters_only:alphanumeric) %>%
  filter(flag == TRUE) 
```

```{r plot, fig.width = 7, fig.height=4}
passwords %>%
  mutate(type = case_when(
    type == "alphanumeric"  ~  paste0("Letters and numbers (N = ", sum(passwords$type == "alphanumeric"), ")"), 
    type == "letters_only"  ~  paste0("Letters only (N = ", sum(passwords$type == "letters_only"), ")"), 
    type == "num_only"      ~  paste0("Numbers only (N = ", sum(passwords$type == "num_only"), ")")
  )) %>%
ggplot() + 
  geom_jitter(aes(x = nchar(password), y = log(offline_crack_sec)),
              fill = paste0(mpr_cols("teal"), "4D"), 
              color = mpr_cols("teal"), 
              size = 3, shape = 21) +
  facet_wrap(~type, nrow = 1) +
  labs(y = "log(Time to crack offline (seconds))", 
       x = "Length (characters)") + 
  scale_y_continuous(breaks = seq(-15, 5, 5), 
                     limits = c(-18, 7)) + 
  scale_x_continuous(breaks = seq(4, 9, 1), 
                     limits = c(3, 9)) + 
  theme_mpr(base_size = 12) + 
  theme(panel.grid.major.x = element_blank()) +
  plot_annotation(title = "Password strength depends on length and composition",
                  subtitle = str_wrap("The time to crack a password increases as the password length increases, regardless of composition, but passwords that use both letters and numbers take longer to crack than passwords of the same length that use only letters or only numbers.", 130),
                  caption = "Source: Information is Beautiful\nGraphic: @marisalyn", 
                  theme = theme_minimal(base_family = "Zilla Slab Medium") + 
                    theme(plot.subtitle = element_text(size = 8)))

ggsave(file.path("C:/Users/mhenry/Documents/tidy_tuesday/output", "passwords_20100114.png"), 
       dpi = 300, width = 8, height = 4.5, type = "cairo")
```

