---
title: "20220104_transitcosts"
output: html_document
---

```{r setup, include=FALSE}
# library(extrafont)
# library(remotes)
# remotes::install_version("Rttf2pt1", version = "1.3.8")
# extrafont::font_import()

extrafont::loadfonts(device = "pdf")

library(tidyverse)
library(ggtext)
#library(patchwork)
library(ggpubr)
library(cowplot)

red <- "#EE3224"
blue <- "#007DB2"
font <- "Roboto Medium"
```

```{r}
# clean up data
df <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-05/transit_cost.csv') %>% 
  filter(country %in% c("US", "CA")) %>%
  mutate(
    country = case_when(
      country=="US" ~ "U.S.", 
      country=="CA" ~ "Canada"
      ),
    cost_km_millions = as.numeric(cost_km_millions)
    ) %>%
  filter(
    !is.na(cost_km_millions), cost_km_millions > 0, 
    !is.na(stations), stations > 0, 
    end_year <= 2021
    ) %>%
  select("country", "city", "line", "length", "stations", "cost_km_millions", "end_year") %>%
  arrange(desc(cost_km_millions)) %>%
  mutate(
    name = paste0("**", line,"**   |   ", city),
    name = fct_reorder(name, cost_km_millions)
    )

df_stations <- df %>% 
  mutate(n_stations = stations)  %>%
  uncount(stations) %>%
  group_by(name) %>%
  mutate(row_num = row_number()) %>%
  ungroup() %>%
  mutate(
    length_frac = length/(2*(n_stations + 1)), 
    station_pos = length_frac*2*row_num, 
    ) 
                          
df_lines <- df %>% 
  mutate(zero = 0, start=0.5, end=length) %>% # hacky fake half rounded edges
  select(name, country, start, end,zero,  cost_km_millions) %>%
  pivot_longer(cols=c(start, end, zero), names_to="v") 
```

```{r}
color_df <- data.frame(
  "country" = c(rep("U.S.  ",2), rep("Canada  ", 2)),
  "value" = c(0,1,0,1)
  )

color_legend <- ggplot(color_df) + 
  geom_line(aes(x=value, y=country, color=country), size=3, lineend="round") + 
  scale_color_manual(values=c("U.S.  " = blue, "Canada  " = red)) +
  lims(x=c(0,1.5)) + 
  theme_void() + 
  theme(
    legend.position="none", 
    plot.margin =margin(0,0,0,0), 
    axis.text.y = element_text(family=font, color="grey40", size=10, hjust=0)
  )

line_df <- data.frame(y="-", zero = 0, start = 0.5, end=2) %>% 
  pivot_longer(cols=c(start, end, zero), names_to="v") 

line_points_df <- data.frame(y="-", "value" = c(1))
  
line_legend <- ggplot()  + 
  geom_line(
    data = line_df %>% filter(v %in% c("zero", "start")),
    aes(x=value, y=y), 
    size=2, color="grey50"
    ) + 
   geom_line(
    data = line_df %>% filter(v %in% c("start", "end")),
    aes(x=value, y=y), 
    size=2, color="grey50", lineend="round"
    ) + 
  geom_point(
    data=line_points_df, 
    aes(x=value, y=y), 
    shape=21, size=4, fill="white", color="grey50", stroke=1.5
    ) +
  scale_color_manual(values=c("U.S." = blue, "Canada" = red), name="") + 
  theme_void() + 
  theme(legend.position="none", plot.margin = margin(0,5,0,0))

line_df_3 <- rbind(line_df, line_df, line_df)
line_df_3$size <- c(rep(100,3), rep(500,3), rep(2000,3))
line_df_3$y <- c(rep("100",3), rep("500",3), rep("2,000", 3))
line_df_3 <- line_df_3 %>% mutate(y = fct_reorder(y, size))

size_legend <- ggplot() + 
  geom_line(
    data = line_df_3 %>% filter(v %in% c("zero", "start")),
    aes(x=value, y=y, size=size, group=y), 
    color="grey50"
    ) + 
  geom_line(
    data = line_df_3 %>% filter(v %in% c("start", "end")),
    aes(x=value, y=y, size=size, group=y), 
    color="grey50", lineend="round"
    ) +
  lims( x=c(-0,2.2)) + 
  theme_void() + 
  theme(
    legend.position="none", 
    plot.margin = margin(5,5,5,5),
    plot.title = element_text(family=font, color="grey40", size=10),
    axis.text.y = element_text(family=font, color="grey40", size=10, hjust=0)
    ) 
  
plot <- ggplot() + 
  geom_line(
    data = df_lines %>% filter(v %in% c("zero", "start")),
    aes(
      x=value, y=name, group=name, 
      size=cost_km_millions, color=country
      )
    ) + 
  geom_line(
    data = df_lines%>% filter(v %in% c("start", "end")),
    aes(
      x=value, y=name, group=name, 
      size=cost_km_millions, color=country
      ),  
    lineend="round"
    ) + 
  geom_point(
    data = df_stations, 
    aes(
      x=station_pos, 
      y=name, 
      size=cost_km_millions, 
      color=country
      ),
    fill="white", 
    stroke=1.5,
    shape=21
    ) + 
  scale_color_manual(values=c("U.S." = blue, "Canada" = red)) + 
  labs( x="\nLength of line (km)", y="") + 
  theme_minimal() + 
  theme(
    legend.position = "none", 
    axis.text.y = ggtext::element_markdown(family=font, size=10, color="grey30"), 
    axis.text.x = element_text(family=font,size=10, color="grey30"), 
    axis.title = ggtext::element_markdown(family=font, color="grey30"),
    panel.grid.major.x = element_line(color="#D3D3D3", size=0.5), 
    panel.grid.major.y = element_blank(), 
    plot.margin = margin(150, 25, 50, 25)
  )  
```


```{r, fig.width=10, fig.height=10}
title <- "Transit project lengths, stations, & costs\nin the U.S. and Canada"
caption <- "Data: Transit Costs Project   |   Graphic: @marisalyn"

ggdraw(plot) +
  draw_label(title, x = 0.05, y = 0.925, fontfamily = font, size = 18, hjust = 0, color="grey30") +
  draw_line(x = c(0.05, 0.95), y = c(0.805, 0.805), color = "#D3D3D3", size = 0.5) +
  draw_line(x = c(0.58, 0.58), y = c(0.825, 0.975), color = "#D3D3D3", size = 0.5)  +
  draw_label("Cost (millions USD)\nper kilometer" , x = 0.62, y = 0.97, fontfamily = font, color="grey40",size = 10, hjust=0,vjust=1) +
  draw_plot(size_legend, height = 0.15, width = 0.15, x = 0.61, y = 0.8, hjust=0)+
  draw_plot(color_legend, height = 0.05, width = 0.12,  x = 0.83, y = 0.82, hjust=0) + 
  draw_label("1 circle = 1 station" , x = 0.83, y = 0.94, fontfamily = font, color="grey40",size = 10, hjust=0,vjust=0) +
  draw_plot(line_legend, height = 0.03, width = 0.12, x = 0.83, y = 0.9, hjust=0) + 
  draw_label(caption, x = 0.95, y = 0.03, fontfamily = font, size = 10, hjust = 1, color="grey30") +
  theme(plot.background = element_rect(fill="white", color = NA))

  
ggsave("output/transit_costs.png",  type = "cairo", width=10, height=8.5, units = "in")

```

