---
title: "dogs.Rmd"
author: "Marisa Henry"
date: "12/16/2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(geofacet)
extrafont::loadfonts(device = "win")
```

```{r load_data}
dog_descriptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-17/dog_descriptions.csv')
```

```{r make_map, fig.width= 12, fig.height=10}
dog_descriptions %>% 
  filter(nchar(contact_state) <= 2, 
         !(contact_state %in% c("NB", "QC"))) %>%
  group_by(contact_state, age) %>% 
  count() %>%
  ungroup() %>%
  mutate(age = factor(age, ordered = T, levels = c("Baby", "Young", "Adult", "Senior"))) %>%
  ggplot() + 
  geom_bar(aes(x = age, y = n), 
           fill = "#2b6f68CC", color = "#2b6f68",  stat = "identity") + 
  scale_y_continuous(labels = comma) + 
  facet_geo(~ contact_state, grid = "us_state_grid2") + 
  labs(x = "", y = "Number of Dogs Available for Adoption",
       title = "Distribution adoptable dogs' age groups across the U.S.\n",
       caption = "Source: https://github.com/the-pudding/data/blob/master/dog-shelters/allDogDescriptions.csv") + 
  theme_minimal(base_family = "Zilla Slab Medium") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.5), 
        panel.grid.major.x = element_blank(), 
        axis.title.y = element_text(margin = unit(c(0, 2, 0, 0), "lines")))

ggsave(file.path("C:/Users/mhenry/Documents/tidy_tuesday/output", "dogs_20191217.png"), width = 10, height = 6, type = "cairo")
```


