---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggstar)
extrafont::loadfonts(device = "win", quiet = T)

records <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-25/records.csv')
drivers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-25/drivers.csv')
```

```{r}
get_png <- function(filename) {
  grid::rasterGrob(png::readPNG(filename), interpolate = TRUE)
}

l <- get_png("input/n64_logo.png")
lakitu <- get_png("input/Lakitu.png")
```

```{r, fig.height=4, fig.width=7.5}
grey <- "#333333"
blue <- "#0000FF"
font <- "Copperplate Gothic Bold"
font2 <- "Garamond"
rr <- records %>%
  filter(type == "Three Lap", track=="Rainbow Road") 

subtitle <- paste0("New shortcuts discovered in Mario Kart's longest track, Rainbow Road, ", 
                   "have cut the world\nrecord time for three laps from nearly 6 ", 
                   "minutes without shortcuts to just ", min(rr$time), " seconds.")


ggplot() + 
  geom_line(
    data = filter(rr, shortcut == "No"), 
    aes(x = date, y = time,  group=shortcut), 
    color = grey, size = 1.3
    ) + 
  geom_star(
    data = filter(rr, shortcut == "No"), 
    aes(x = date, y = time, group=shortcut), 
    color = grey,  size = 2.1, fill="white", starshape = 1
    ) +
  geom_line(
    data = filter(rr, shortcut == "Yes"), 
    aes(x = date, y = time, color = date, group=shortcut), 
    size = 1.3
    ) + 
  geom_star(
    data = filter(rr, shortcut == "Yes"), 
    aes(x = date, y = time, color = date, group=shortcut), 
    size = 2.1, fill="white", starshape = 1
    ) +
  annotate(
    "label", 
    x = ymd("2019-01-01"), 
    y = max(filter(rr, shortcut == "No", date >= ymd("20170101"))$time) + 25, 
    label = "Without shortcuts", family=font2,
    hjust = 1, lineheight = 1, 
    fill = "white",label.size = NA,size = 3.3, color = grey
    ) + 
  annotate(
    "label", 
    x = ymd("2019-01-01"), 
    y = max(filter(rr, shortcut == "Yes", date >= ymd("20170101"))$time) + 25, 
    label = "With shortcuts", family=font2,
    hjust = 1, lineheight = 1, 
    fill = "white", label.size = NA,size = 3.3, color = blue
    ) + 
  annotation_custom(
    lakitu, 
    xmin = ymd("2019-01-01"), xmax = ymd("2022-01-01"), 
    ymin = 390, ymax = 520
    ) + 
  coord_cartesian(clip="off") + 
  scale_color_gradientn(colours = rainbow(6)) +
  scale_x_date(date_breaks = "2 year", date_labels = "%Y") +
  scale_y_continuous(limits = c(0, 420), breaks = seq(0, 420, 60)) + 
  labs(
    x = "", 
    y = "Time (seconds)\n",
    title = "FINISH! Mario Kart 64 Rainbow Road World Records", 
    subtitle = subtitle, 
    caption = "Source: Mario Kart World Records | #TidyTuesday | Viz: @marisalyn"
    ) + 
  theme_minimal(base_family = font2) + 
  theme(
    legend.position = "none", 
    plot.title = element_text(family = font, color=grey), 
    plot.subtitle = element_text(color=grey, size =8), 
    plot.caption = element_text(color=grey, size =8), 
    axis.text = element_text(size = 8, color= grey), 
    axis.title = element_text(size=8, color=grey),
    axis.text.x = element_text(angle=90, vjust = 0.5)
    )

ggsave(file.path("./output", "20210527_mariokart.png"), 
       dpi = 300, width = 7.5, height = 4, type = "cairo")
```

