---
title: "tbi_20200327"
author: "Marisa Henry"
date: "3/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
library(plotMPR) #internal package
library(ggwaffle)

extrafont::loadfonts(device = "win", quiet = TRUE)

update_geom_defaults("text", 
                     list(hjust = 0.5, 
                          lineheight = .8,
                          family = "Zilla Slab Medium", 
                          color = mpr_cols("green")))
```

```{r}
tbi_age <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-24/tbi_age.csv')

age_groups <- c("0-4", 
                "5-14", 
                "15-24", 
                "25-34", 
                "35-44", 
                "45-54",  
                "55-64", 
                "65-74", 
                "75+")

injury_mechanisms <- c("Assault" = mpr_cols("red"),
                       "Intentional self-harm" = mpr_cols("dark blue"), 
                       "Motor vehicle crashes" = mpr_cols("yellow"), 
                       "Unintentional falls" = mpr_cols("green"), 
                       "Uninentionally struck by/against object" = mpr_cols("teal"), 
                       "Other" = mpr_cols("grey 75"))

types <- c("Emergency department visit", 
           "Hospitalizations", 
           "Deaths")

tbi_age <- tbi_age %>% 
  filter(age_group != "Total", age_group != "0-17") %>%
  group_by(type) %>%
  mutate(n_by_type = comma(round(sum(number_est, na.rm = TRUE), 0))) %>%
  ungroup() %>%
  mutate(age_group = factor(age_group, age_groups), 
         type = str_to_sentence(type), 
         type = paste0(type, " (N = ", n_by_type, ")"),
         injury_mechanism = str_to_sentence(injury_mechanism), 
         injury_mechanism = case_when(
           grepl("Other", injury_mechanism) ~ "Other", 
           grepl("struck", injury_mechanism) ~ "Uninentionally struck by/against object",
           TRUE ~ injury_mechanism
         ), 
         injury_mechanism = factor(injury_mechanism, names(injury_mechanisms))) %>%
  group_by(injury_mechanism, type, age_group) %>%
  mutate(number_est = mean(number_est)) %>%
  slice(1) %>%
  group_by(age_group, type) %>%
  mutate(n_per_age_type = sum(number_est, na.rm = TRUE)) %>%
  group_by(type) %>%
  mutate(per = number_est/n_per_age_type*100) %>%
  ungroup() %>%
  replace_na(list(per = 0)) 

types <- c(unique(tbi_age$type)[grepl("Emergency", unique(tbi_age$type))], 
          unique(tbi_age$type)[grepl("Hosp", unique(tbi_age$type))],
          unique(tbi_age$type)[grepl("Death", unique(tbi_age$type))])

tbi_age <- tbi_age %>%
  mutate(type = factor(type, types))
```

```{r, fig.height=8, fig.width=12}
ggplot() +
  geom_bar(data = tbi_age, 
           aes(x = age_group, y = per, fill = injury_mechanism, color = injury_mechanism), 
          stat = "identity") +
  facet_wrap(~ type, ncol = 1) + 
  scale_fill_manual(values = paste0(injury_mechanisms, "CC"), name = "") + 
  scale_color_manual(values = injury_mechanisms, "CC", name = "") + 
  scale_y_continuous(limits = c(0, 105), expand = c(0.0, 0.0)) +
  theme_mpr() +
  labs(x = "Age group", y = "Percent", 
       caption = "Data: CDC (2014) \nVisualization: @marisalyn", 
       title = "Traumatic brain injuries in 2014",
       subtitle = "The cause and impact of traumatic brain injuries vary by age\n") +
  theme(legend.position = "bottom", 
        panel.grid.major.x = element_blank(), 
        strip.text = element_text(size = 10)) + 
  coord_cartesian(clip = "off") + 
  guides(col = guide_legend(nrow = 3), 
         fill = guide_legend(nrow = 3))

ggsave("./output/tbi_20200327.png", width = 7, height = 9, dpi = 600, type = "cairo")
```

```{r}
ggplot() +
  geom_area(data = tbi_age, aes(x = age_group, y = per, group = injury_mechanism,  fill = injury_mechanism)) +
  theme_mpr() + 
  theme(legend.position = "none")
```


