---
title: "Video games"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggtext)
extrafont::loadfonts(device = "win", quiet = T)

games <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-16/games.csv')


```

```{r}
summary(games)
```

```{r}
oatbf <- games %>%
  filter(grepl("blind forest", tolower(gamename))) %>%
  mutate(ym = ymd(paste0(year, month, 1)))

assertthat::assert_that(length(unique(oatbf$gamename)) == 1)
```

```{r, fig.width =7}
caption <- "\n\nSource: Steam | #TidyTuesday | Viz: @marisalyn"

title <- "Ori and the Blind Forest: Definitive Edition"

subtitle <- "Average number of concurrent players of on Steam, by month"

label <- str_wrap("The average number of concurrent players peaked in March 2020, coninciding with the release date of the game's sequel, Ori and the Will of the Wisps, and global lockdowns due to the COVID-19 pandemic", 50)

orange <- "#E04C28"
purple <- "#905D95"
blue <- "#3F5A85"
mid_blue <- "#d3dbe6"
light_blue <- "#F5FCFF"

ggplot(oatbf) +
  geom_line(
    aes(x = ym, y = avg), 
    color = orange, 
    size = 1.5
    ) + 
  geom_point(
    aes(x = ym, y = avg), 
    color = orange, 
    fill = light_blue,
    shape = 21,
    stroke = 1.5,
    size = 1.5
  ) + 
  annotate(
    "label", x = ymd("2018-06-01"), y = 1500, label = label, 
    hjust = 0.5, 
    lineheight = 1, 
    fill = light_blue,
    label.size = NA,
    size = 3.3, 
    family = "Segoe UI", 
    color = purple
    ) + 
  annotate(
    "curve", x = ymd("2019-01-01"), y = 1750, 
    xend = ymd("2020-02-01"), yend = max(oatbf$avg),
    colour = purple,
    size = 0.8,
    curvature = -0.2,
    arrow = arrow(length = unit(0.03, "npc"), type = "closed"),
    inherit.aes = FALSE
    ) + 
  labs(title = title, subtitle = subtitle, caption = caption) + 
  scale_y_continuous(labels = scales::comma) +
  theme_minimal(base_family = "Segoe UI", base_size = 12) + 
  theme(
    plot.title = element_text(color = orange, face = "bold"), 
    plot.subtitle = element_text(color = blue, face = "italic", size = 10),
    plot.caption = element_text(color = blue), 
    axis.title = element_blank(),
    axis.text = element_text(color = blue),
    panel.grid = element_line(color = mid_blue),
    panel.grid.minor.x = element_blank(),
    panel.background = element_rect(color=light_blue, fill=light_blue),
    plot.background = element_rect(color=light_blue, fill=light_blue)
  )

ggsave(file.path("./output", "steam_20210317.png"), 
       dpi = 300, width = 7.5, height = 4, type = "cairo")
```


